spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    show-sql: false

server:
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /payment/api
  port: 8080